include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = MiniBrowser

MiniBrowser_OBJC_FILES = main.m

MiniBrowser_OBJCFLAGS = -fobjc-arc
MiniBrowser_RESOURCE_FILES = Resources/Info.plist

include $(GNUSTEP_MAKEFILES)/application.make
